//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

pub use super::app_config::Entity as AppConfig;
pub use super::rule::Entity as Rule;
pub use super::capture::Entity as Capture;
pub use super::handler::Entity as Handler;
